//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildBind
    {
        public int ID { get; set; }
        public string deviceId { get; set; }
        public string token { get; set; }
        public Nullable<int> sceneId { get; set; }
        public Nullable<System.DateTime> BindDate { get; set; }
    }
}
