//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsetTencentUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TencentUser
    {
        public int Id { get; set; }
        public string OpenId { get; set; }
        public string GUID { get; set; }
        public string License { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string DevModel { get; set; }
        public Nullable<System.DateTime> ActivateDate { get; set; }
        public string Version { get; set; }
    }
}
