//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsetTencentUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int Id { get; set; }
        public Nullable<int> Tid { get; set; }
        public string Title { get; set; }
        public string Cover { get; set; }
        public string Describe { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> State { get; set; }
        public string Definition { get; set; }
        public string Advertisement { get; set; }
    }
}
