//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsetTencentUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoUrl
    {
        public int Id { get; set; }
        public Nullable<int> Vid { get; set; }
        public string Source { get; set; }
        public string Path { get; set; }
        public string TempPath { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Definition { get; set; }
        public string Advertisement { get; set; }
    }
}
